import type { HelpArticle } from './types';

/**
 * English help corpus.
 *
 * Authored, not generated: every step names a real control, quoted
 * exactly as it appears in the UI, so a renamed button is a greppable
 * break rather than a silently wrong instruction. All content is
 * gym-admin only — nothing here describes the platform/super-admin app.
 *
 * `keywords` carries the words admins actually type but that don't
 * appear in the title — synonyms ("cash", "sign up", "invoice") and the
 * phrasings the search tests pin down. Search requires every query
 * token to hit somewhere, so a missing synonym is a missing result.
 *
 * The Arabic corpus in ./articles.ar.ts must mirror this file's `id`
 * and `category` set exactly — tests/lib/help-articles.test.ts enforces
 * both, plus that no Arabic title was left in English.
 */
export const ARTICLES_EN: HelpArticle[] = [
  // ── Getting started ─────────────────────────────────────────────────
  {
    id: 'setup-order',
    category: 'getting-started',
    title: 'How do I set my gym up for the first time?',
    summary: 'The order to do things in so nothing blocks you later.',
    steps: [
      'Add your branch under Settings → "Branches & Operations" → "Add Branch".',
      'Add at least one studio or room — you cannot put a class on the calendar without one.',
      'Fill in your gym name and logo under Settings → "Gym Profile", and your hours under "Operating Hours".',
      'Create your membership plans under "Subscription Plans".',
      'Add your trainers under "Services".',
      'Create your classes, then put them on the calendar and publish the schedule.',
      'Add your members, give each one a plan, and record their payment.',
    ],
    notes: [
      'The branch and studio come first — classes, trainers and the check-in QR code all need them.',
      'If you only have one location, branch dropdowns are hidden and filled in for you.',
      'Plans come before members: you cannot give someone a plan that does not exist yet.',
    ],
    related: ['add-member', 'create-plan', 'schedule-class', 'publish-schedule'],
    keywords: [
      'setup', 'set up', 'start', 'begin', 'onboarding', 'first time',
      'new gym', 'getting started', 'configure', 'order',
    ],
  },
  {
    id: 'dashboard-tour',
    category: 'getting-started',
    title: 'What do the numbers on the Overview screen mean?',
    summary: 'A quick tour of the home screen figures.',
    steps: [
      'Open "Overview" from the sidebar.',
      'Read the four cards: "Total Members", "Active Staff", "This Month Revenue" and "Total Revenue".',
      'For anything deeper, use "Analytics" instead.',
    ],
    notes: ['If a card shows zero unexpectedly, refresh the page — the figures load separately from the rest of the screen.'],
    related: ['view-analytics', 'add-member', 'record-payment'],
    keywords: ['dashboard', 'overview', 'home', 'stats', 'statistics', 'numbers', 'summary', 'revenue'],
    href: '/dashboard',
  },
  {
    id: 'view-analytics',
    category: 'getting-started',
    title: 'How do I see reports and export them?',
    summary: 'Read the analytics screens and download the numbers.',
    steps: [
      'Go to "Analytics" in the sidebar.',
      'Pick a tab: "Dashboard", "Member Growth & Churn", "Revenue & Payments" or "Class Attendance".',
      'Choose a period with the preset buttons, or set a "Custom:" range and click "Apply".',
      'Click "Export" and choose "CSV", "Excel (.xlsx)" or "Print / PDF".',
    ],
    notes: [
      'The export only covers the tab you are looking at, so switch tabs and export again for the rest.',
      'Switching tabs keeps the date range you last applied.',
    ],
    related: ['memberships-view', 'payment-history', 'dashboard-tour'],
    keywords: [
      'analytics', 'reports', 'export', 'churn', 'growth', 'revenue report',
      'statistics', 'kpi', 'excel', 'print', 'pdf', 'download report',
    ],
    href: '/dashboard/analytics',
  },

  // ── Members ─────────────────────────────────────────────────────────
  {
    id: 'add-member',
    category: 'members',
    title: 'How do I create a member?',
    summary: 'Add a new member record from the Members screen.',
    steps: [
      'Go to "Members" in the sidebar.',
      'Click "Add Member" at the top right.',
      'Under "Personal Info", fill in "Full Name" and "Email" — both are required.',
      'Optionally add "Phone", "Gender", "Date of Birth" and "Address".',
      'Click "Add Member" to save.',
    ],
    notes: [
      'This creates the person, not their membership. Give them a plan next, then record the payment.',
      'The member number is assigned automatically — the list shows "No Member ID yet" until it appears.',
    ],
    related: ['assign-plan', 'record-payment', 'edit-member'],
    keywords: [
      'create member', 'new member', 'add client', 'register', 'sign up', 'signup',
      'enroll', 'subscriber', 'customer', 'join', 'add person',
    ],
    href: '/dashboard/members',
  },
  {
    id: 'edit-member',
    category: 'members',
    title: 'How do I edit a member’s details?',
    summary: 'Change a name, phone number or any other detail.',
    steps: [
      'Go to "Members".',
      'Find them — you can search by name, email, phone or member number.',
      'Click the "Edit member" action on their row.',
      'Change what you need in the "Edit Member" box.',
      'Click "Save Changes".',
    ],
    notes: ['Editing is done from the list, not from inside their profile page.'],
    related: ['add-member', 'deactivate-member', 'member-photo'],
    keywords: ['edit', 'update member', 'change details', 'fix name', 'phone', 'correct', 'wrong email'],
    href: '/dashboard/members',
  },
  {
    id: 'member-photo',
    category: 'members',
    title: 'How do I add a member’s photo?',
    summary: 'Upload or remove the photo on a member profile.',
    steps: [
      'Go to "Members" and click the member to open their profile.',
      'Click their picture at the top of the page.',
      'Choose the image file.',
      'To take it off again, use "Remove photo".',
    ],
    notes: ['Photos must be JPG, PNG, GIF or WebP and under 5 MB.'],
    related: ['edit-member', 'add-member'],
    keywords: ['photo', 'picture', 'avatar', 'image', 'headshot', 'profile picture', 'upload photo'],
    href: '/dashboard/members',
  },
  {
    id: 'assign-plan',
    category: 'members',
    title: 'How do I give a member a membership plan?',
    summary: 'Assign or change the plan on a member’s profile.',
    steps: [
      'Go to "Members" and click the member to open their profile.',
      'Click "Assign Plan" — it reads "Change Plan" if they already have one.',
      'Pick the plan under "Select Plan *".',
      'If a discount or promo code applies, choose it under "Apply Discount".',
      'Set the "Start Date *".',
      'Check the summary — plan, expiry and total — then confirm.',
    ],
    notes: [
      'Create your plans first, or you will see "No plans available. Create plans first."',
      'This creates a payment marked as pending — you still need to collect the money and mark it paid.',
      'Changing a plan cancels and replaces the current one.',
    ],
    related: ['create-plan', 'record-payment', 'renew-membership', 'remove-plan'],
    keywords: [
      'assign plan', 'give plan', 'subscribe', 'subscription', 'membership',
      'change plan', 'add plan to member', 'sell membership', 'sign up plan',
    ],
    href: '/dashboard/members',
  },
  {
    id: 'renew-membership',
    category: 'members',
    title: 'How do I renew or extend a membership?',
    summary: 'Push an expiry date out, or add more sessions.',
    steps: [
      'Open the member’s profile from "Members".',
      'To push the expiry date out, click "Extend", pick one of the quick options or type your own number of days, check the "New expiry:" preview and confirm.',
      'To add more sessions, click "Add Sessions", choose or type an amount, and confirm.',
      'To start a fresh term on a different plan, use "Change Plan".',
    ],
    notes: [
      '"Extend" only appears on time-based plans; "Add Sessions" only on session plans. You will see whichever fits their plan.',
      'If their membership already expired, extending counts from today rather than from the old expiry date.',
      'Remember to record the payment for the renewal.',
    ],
    related: ['assign-plan', 'record-payment', 'freeze-membership'],
    keywords: [
      'renew', 'renewal', 'extend', 'expiry', 'expire', 'top up', 'add sessions',
      'more sessions', 'prolong', 'continue membership', 'expired',
    ],
    href: '/dashboard/members',
  },
  {
    id: 'freeze-membership',
    category: 'members',
    title: 'How do I freeze or pause a membership?',
    summary: 'Put a membership on hold and push the expiry out to match.',
    steps: [
      'Open the member’s profile from "Members".',
      'Click "Freeze".',
      'Choose the number of days under "How many days?".',
      'Check the "New expiry:" preview and click "Freeze Plan".',
      'To end a freeze early, click "Unfreeze" and then "Resume Now".',
    ],
    notes: [
      'The "Freeze" button only appears if freezing is switched on for their plan and the plan is time-based. Session-only plans cannot be frozen.',
      'When the allowance runs out the button is greyed out and reads "All freeze days used" or "Max freeze count reached".',
      'You cannot freeze for longer than the membership has left to run.',
      'Freezes do not lift by themselves. Watch for the "Freeze lapsed" warning on the "Memberships" tab and unfreeze those manually.',
    ],
    related: ['renew-membership', 'assign-plan', 'create-plan'],
    keywords: [
      'freeze', 'pause', 'hold', 'suspend membership', 'on hold', 'stop temporarily',
      'travel', 'injury', 'unfreeze', 'resume', 'holiday',
    ],
    href: '/dashboard/members',
  },
  {
    id: 'transfer-membership',
    category: 'members',
    title: 'How do I transfer a membership to another member?',
    summary: 'Move what is left of a membership to someone else.',
    steps: [
      'Open the profile of the member giving it up.',
      'Click "Transfer".',
      'Under "Search destination member", find who is receiving it.',
      'Click "Review" and check the "From" and "To" panels.',
      'Click "Confirm Transfer".',
    ],
    notes: [
      'This cancels the first member’s plan and cannot be undone.',
      'The receiving member sees it on their "Sessions History" tab.',
    ],
    related: ['assign-plan', 'freeze-membership'],
    keywords: ['transfer', 'move membership', 'give sessions', 'share', 'reassign', 'swap', 'hand over'],
    href: '/dashboard/members',
  },
  {
    id: 'remove-plan',
    category: 'members',
    title: 'How do I remove a member’s plan?',
    summary: 'Detach the current plan from a member.',
    steps: [
      'Open the member’s profile from "Members".',
      'Click "Detach Plan".',
      'Click "Confirm" on the "Remove plan?" prompt.',
    ],
    notes: ['This sets the member to inactive. To swap them onto a different plan instead, use "Change Plan".'],
    related: ['assign-plan', 'deactivate-member'],
    keywords: ['remove plan', 'detach', 'cancel membership', 'end plan', 'take away plan', 'stop subscription'],
    href: '/dashboard/members',
  },
  {
    id: 'deactivate-member',
    category: 'members',
    title: 'How do I deactivate a member?',
    summary: 'Switch someone off without losing their history.',
    steps: [
      'Go to "Members" and find them.',
      'Click the "Deactivate member" action and confirm.',
      'To bring them back later, use "Reactivate member".',
    ],
    notes: ['Their data is kept and can be reactivated at any time.'],
    related: ['edit-member', 'remove-plan', 'add-member'],
    keywords: [
      'deactivate', 'remove member', 'cancel member', 'archive', 'quit', 'left',
      'suspend', 'disable member', 'delete member',
    ],
    href: '/dashboard/members',
  },
  {
    id: 'verify-email',
    category: 'members',
    title: 'How do I verify a member’s email?',
    summary: 'Confirm an email address is valid.',
    steps: [
      'Go to "Members", or open the member’s profile.',
      'Click the "Verify email" action next to the "Unverified" badge.',
      'Confirm.',
    ],
    notes: ['The action only shows when the member has an email that is not yet verified.'],
    related: ['edit-member', 'add-member'],
    keywords: ['verify email', 'unverified', 'confirm email', 'validate', 'email badge'],
    href: '/dashboard/members',
  },
  {
    id: 'export-members',
    category: 'members',
    title: 'How do I export my member list?',
    summary: 'Download members as a spreadsheet.',
    steps: [
      'Go to "Members".',
      'Click "Export" to open "Export Members".',
      'Choose "CSV" or "Excel" under "Export Format".',
      'Under "Select Members", keep "Select all" or tick the ones you want.',
      'Click "Export CSV" or "Export EXCEL".',
    ],
    notes: [
      'This exports only the page of members you are currently viewing.',
      'For a full list of memberships, use the "Export" button on the "Memberships" tab instead — that one covers everything matching your filters.',
    ],
    related: ['memberships-view'],
    keywords: ['export', 'download', 'csv', 'excel', 'xlsx', 'spreadsheet', 'backup', 'member list'],
    href: '/dashboard/members',
  },
  {
    id: 'memberships-view',
    category: 'members',
    title: 'How do I see who is expiring soon?',
    summary: 'Work your renewals and follow-ups from one list.',
    steps: [
      'Go to "Members".',
      'Switch to the "Memberships" tab.',
      'Click the "Expiring in {n} days" card, or set your own number under "Expiring threshold".',
      'Narrow it further with "Date filters" if you need to.',
      'Click "Export" to take the list away for calls.',
    ],
    notes: [
      'The other cards let you jump to "Awaiting payment", "Frozen" and "Expired" members.',
      'The list shows subscriptions only by default. Switch the source filter to "All sources" to also see transferred sessions.',
      'Your filters are remembered when you come back to this screen.',
    ],
    related: ['renew-membership', 'export-members', 'send-reminders'],
    keywords: [
      'expiring', 'expire soon', 'renewals', 'follow up', 'due', 'lapsed',
      'about to end', 'who needs renewing', 'churn', 'memberships',
    ],
    href: '/dashboard/members?view=memberships',
  },
  {
    id: 'add-lead',
    category: 'members',
    title: 'How do I add a lead or enquiry?',
    summary: 'Track someone interested in joining before they sign up.',
    steps: [
      'Go to "Sales & Leads" in the sidebar.',
      'Open the "Leads" tab and click "New lead".',
      'Enter the "Name" and "Phone" — both required.',
      'Optionally add their email, where they came from, and what they are interested in.',
      'Leave "Assign to me" ticked if you will follow up, then click "Create lead".',
    ],
    notes: [
      'If that phone number already exists you will be warned, and can open the existing lead or add it anyway.',
      'Move a lead along by opening it and clicking "Advance to …", or by dragging its card on the "Pipeline" tab.',
    ],
    related: ['convert-lead', 'add-member'],
    keywords: [
      'lead', 'enquiry', 'inquiry', 'prospect', 'walk in', 'interested',
      'sales', 'pipeline', 'follow up', 'new enquiry',
    ],
    href: '/dashboard/sales',
  },
  {
    id: 'convert-lead',
    category: 'members',
    title: 'How do I turn a lead into a member?',
    summary: 'Close the sale and record what they agreed to.',
    steps: [
      'Go to "Sales & Leads" and open the lead.',
      'On the "Offers" tab, create an offer with the price you quoted.',
      'Move the lead to the "Offer presented" stage.',
      'Click "Convert", then choose the accepted offer, the payment method, the final price and the start date.',
      'Click "Convert".',
    ],
    notes: [
      'You must create an offer first — converting records which offer they accepted.',
      'Once converted, the lead becomes read-only.',
      'If they do not join, use "Mark lost" with a reason. You can set a date to get back in touch later.',
    ],
    related: ['add-lead', 'add-member', 'record-payment'],
    keywords: [
      'convert', 'close sale', 'signed up', 'won', 'became member',
      'lost lead', 'mark lost', 'quote', 'offer',
    ],
    href: '/dashboard/sales',
  },
  {
    id: 'guest-invitations',
    category: 'members',
    title: 'How do guest invitations work?',
    summary: 'Members invite guests from the app; you track and cancel them here.',
    steps: [
      'Go to "Guest Invitations" in the sidebar.',
      'Review them by status: "Pending", "Accepted", "Active", "Expired" or "Invalidated".',
      'To cancel an unused one, click "Invalidate" on its row and confirm.',
    ],
    notes: [
      'You cannot create invitations from here — members send them from the mobile app. This screen is for tracking and cancelling.',
      '"Invalidate" only appears on pending invitations, and gives the invite back to the member.',
      'How many invites a member gets is set on their plan, under "Guest Invitations".',
    ],
    related: ['create-plan', 'add-member'],
    keywords: [
      'guest', 'invitation', 'invite', 'guest pass', 'bring a friend',
      'day pass', 'visitor', 'invalidate', 'revoke invite',
    ],
    href: '/dashboard/invitations',
  },

  // ── Payments ────────────────────────────────────────────────────────
  {
    id: 'record-payment',
    category: 'payments',
    title: 'How do I create a payment?',
    summary: 'Record cash, card or a bank transfer, or send a payment link.',
    steps: [
      'Go to "Payments" in the sidebar.',
      'Click "Record Payment" to open "Create Payment".',
      'Search for the member and select them.',
      'Choose what they are paying for under "Service / Item", or pick "Other (custom description)" and type it.',
      'Check the "Amount" and change it if needed.',
      'Pick the "Payment Method" — "Cash", "Bank Transfer", "Card", "Other" or "Payment Link".',
      'Leave the "Status" on "Paid" if you have the money, then click "Create Payment".',
    ],
    notes: [
      'If you pick a membership plan here, it also gives that plan to the member — this is the quickest way to sell or renew a membership.',
      'For "Payment Link" you must enter the "Customer Mobile Number" with the country code, then click "Generate Payment Link". You can then "Copy Link" or "Send via WhatsApp", and the status updates itself once they pay.',
      'If a promotion or promo code applies, you can choose it before saving.',
    ],
    related: ['refund-payment', 'payment-history', 'mark-paid', 'assign-plan'],
    keywords: [
      'create payment', 'record payment', 'take payment', 'collect', 'cash', 'card',
      'invoice', 'receipt', 'money', 'paid', 'charge', 'bill', 'pay', 'transaction',
      'bank transfer', 'payment link', 'sell membership', 'member', 'from a member',
    ],
    href: '/dashboard/payments',
  },
  {
    id: 'mark-paid',
    category: 'payments',
    title: 'How do I mark a payment as paid?',
    summary: 'Confirm a pending payment once the money arrives.',
    steps: [
      'Go to "Payments".',
      'Click the "Pending" or "Overdue" card to find it.',
      'Click "Mark as Paid" on the row.',
      'Check the details and click "Update Payment".',
    ],
    notes: ['"Mark as Overdue" and "Mark as Pending" are on the same row if you need to move it back.'],
    related: ['record-payment', 'send-reminders', 'payment-history'],
    keywords: [
      'mark paid', 'pending', 'overdue', 'settle', 'confirm payment', 'received',
      'status', 'money came in', 'clear payment',
    ],
    href: '/dashboard/payments',
  },
  {
    id: 'refund-payment',
    category: 'payments',
    title: 'How do I refund a payment?',
    summary: 'Give back all or part of a payment.',
    steps: [
      'Go to "Payments".',
      'Find the payment — search by member name, email or member number.',
      'Click "Process Refund" on the row.',
      'Choose "Full Refund" or "Partial Refund" and enter the amount.',
      'Type the "Reason" — this is required.',
      'Click the refund button to confirm.',
    ],
    notes: [
      'Refunding is only possible on payments already marked as paid.',
      'If it was paid by card through the payment gateway, the money goes back to their card automatically. Cash and transfers you hand back yourself — this just records it.',
      'A refund does not remove their plan or sessions. Adjust those on their profile if you need to.',
    ],
    related: ['record-payment', 'payment-history', 'view-invoice'],
    keywords: [
      'refund', 'money back', 'reverse', 'return payment', 'chargeback',
      'cancel payment', 'reimburse', 'partial refund',
    ],
    href: '/dashboard/payments',
  },
  {
    id: 'payment-history',
    category: 'payments',
    title: 'How do I see what a member has paid?',
    summary: 'Read one member’s payments and download a statement.',
    steps: [
      'Go to "Members" and open the member’s profile.',
      'Switch to the "Payments" tab.',
      'Read "Total Paid", "Outstanding" and "Refunded" at the top, with the full list below.',
      'Use "Filter Period" to narrow it to dates.',
      'Click "Download Statement" for a copy.',
    ],
    notes: ['For gym-wide figures, use the "Payments" screen, which shows "Daily Revenue", "Paid", "Pending" and "Overdue".'],
    related: ['record-payment', 'refund-payment', 'view-invoice'],
    keywords: [
      'payment history', 'statement', 'what did they pay', 'outstanding', 'balance',
      'owes', 'unpaid', 'transactions', 'receipts', 'account',
    ],
    href: '/dashboard/members',
  },
  {
    id: 'view-invoice',
    category: 'payments',
    title: 'How do I get a receipt or invoice?',
    summary: 'Open, print or email the receipt for a payment.',
    steps: [
      'Go to "Payments".',
      'Find the payment row.',
      'Click "View Receipt" (or "View Invoice" if it is not paid yet).',
      'Click "Print / PDF", or "Send Email" to email it to the member.',
    ],
    notes: ['"Send Email" needs the member to have an email address on file.'],
    related: ['record-payment', 'payment-history', 'contract-terms'],
    keywords: ['invoice', 'receipt', 'print', 'proof of payment', 'bill', 'email receipt', 'pdf'],
    href: '/dashboard/payments',
  },
  {
    id: 'send-reminders',
    category: 'payments',
    title: 'How do I chase members who owe money?',
    summary: 'Email everyone with an overdue payment.',
    steps: [
      'Go to "Payments".',
      'Click "Send Reminders" at the top — it shows how many are overdue.',
      'Tick who to contact, or use "Select all".',
      'Click "Send {n} Reminders".',
    ],
    notes: [
      'The button only appears when someone actually has an overdue payment.',
      'Members without an email address show "No email on file" and cannot be selected.',
    ],
    related: ['mark-paid', 'payment-history', 'memberships-view'],
    keywords: [
      'reminder', 'chase', 'overdue', 'debt', 'owes', 'unpaid', 'notify',
      'collect', 'late payment', 'email reminder',
    ],
    href: '/dashboard/payments',
  },
  {
    id: 'payment-gateway',
    category: 'payments',
    title: 'How do I set up card payments in the app?',
    summary: 'Enter your payment gateway details so members can pay by card.',
    steps: [
      'Go to "Settings" and open the "Mobile App & Payments" section.',
      'Find the "Payment Gateway" card.',
      'Enter the "Secret Key", "Public Key" and "Card Integration ID" — all three are required.',
      'Add the ValU or Apple Pay IDs too if you use them.',
      'Click "Save Payment Config".',
    ],
    notes: [
      'You get these details from your payment provider.',
      'Saved keys are never shown again for security. If you save new ones they replace the old ones completely — so re-enter the optional IDs too, or those methods will stop working.',
      'Check "Mobile Payments" is switched on in the same section, or payment buttons stay hidden in the app.',
    ],
    related: ['record-payment', 'mobile-app-settings'],
    keywords: [
      'payment gateway', 'card payments', 'paymob', 'online payments', 'apple pay',
      'valu', 'checkout', 'keys', 'integration',
    ],
    href: '/dashboard/settings',
  },

  // ── Plans ───────────────────────────────────────────────────────────
  {
    id: 'create-plan',
    category: 'plans',
    title: 'How do I create a membership plan?',
    summary: 'Set up a plan members can join.',
    steps: [
      'Go to "Subscription Plans" in the sidebar.',
      'Click "New Plan".',
      'Enter the "Plan Name *" — for example "Gold Monthly" or "10-Session Pack".',
      'Choose the "Plan Type *" (see below).',
      'Set the price, and either the duration, the number of sessions, or both.',
      'Add what the plan includes under "Facilities & Classes Access".',
      'Click "Create Plan".',
    ],
    notes: [
      'There are three types, and your choice changes the rest of the form: "Duration" is time-based with gym access, "Sessions Only" is a pack of sessions with studio access, and "Duration + Sessions" gives both.',
      'Pick the type carefully — it decides how the membership runs out and what the member can use.',
      'To let members pause the plan, switch on "Freeze Plan" and set the maximum days and number of freezes. This is not available on session-only plans.',
      'To give members guest passes, switch on "Guest Invitations" and set how many they get.',
    ],
    related: ['edit-plan', 'assign-plan', 'deactivate-plan', 'plan-promo-price'],
    keywords: [
      'create plan', 'new plan', 'membership plan', 'package', 'tier', 'pricing',
      'subscription plan', 'sessions plan', 'duration plan', 'monthly plan',
    ],
    href: '/dashboard/plans',
  },
  {
    id: 'edit-plan',
    category: 'plans',
    title: 'How do I change a plan’s price?',
    summary: 'Edit an existing plan.',
    steps: [
      'Go to "Subscription Plans".',
      'Find the plan — you can search by name or description.',
      'Click "Edit plan" on its row.',
      'Change the price or anything else.',
      'Click "Save changes".',
    ],
    notes: [
      'This does not change what current members already pay — it applies to new sign-ups and renewals.',
      'For a temporary price cut, use a promotion instead so the old price comes back automatically.',
    ],
    related: ['create-plan', 'plan-promo-price', 'deactivate-plan'],
    keywords: ['edit plan', 'change price', 'pricing', 'increase price', 'update plan', 'cost', 'fee'],
    href: '/dashboard/plans',
  },
  {
    id: 'deactivate-plan',
    category: 'plans',
    title: 'How do I stop selling a plan?',
    summary: 'Deactivate a plan so it can no longer be assigned.',
    steps: [
      'Go to "Subscription Plans".',
      'Find the plan and click "Deactivate".',
      'Read the summary of who is affected, then click "Deactivate Plan".',
      'Use "Activate" to bring it back later.',
    ],
    notes: [
      'Members already on the plan keep it and carry on as normal — the dialog tells you how many that is.',
      'It only disappears from the list you assign new plans from.',
    ],
    related: ['create-plan', 'edit-plan'],
    keywords: [
      'deactivate plan', 'disable', 'retire', 'stop selling', 'hide plan',
      'archive plan', 'discontinue', 'old plan',
    ],
    href: '/dashboard/plans',
  },

  // ── Classes & schedule ──────────────────────────────────────────────
  {
    id: 'create-class',
    category: 'classes',
    title: 'How do I create a class?',
    summary: 'Set up the class you will later put on the calendar.',
    steps: [
      'Go to "Classes & Schedule".',
      'Open the "Classes" tab.',
      'Click "New Class".',
      'Enter the "Class Name", and pick the "Branch" if you have more than one.',
      'Optionally set the "Class Type", "Specialist", "Location / Room", "Color" and an image.',
      'Click "Create Class".',
    ],
    notes: [
      'A class on its own does not appear on the calendar — you schedule sessions from it next.',
      'If a class is deactivated it disappears from the scheduling list. That is usually why a class seems to be missing.',
    ],
    related: ['schedule-class', 'create-class-type', 'add-trainer'],
    keywords: [
      'create class', 'new class', 'class template', 'add class', 'yoga',
      'crossfit', 'group class', 'spinning', 'zumba',
    ],
    href: '/dashboard/classes',
  },
  {
    id: 'create-class-type',
    category: 'classes',
    title: 'How do I add a class type?',
    summary: 'Manage the class categories you can choose from.',
    steps: [
      'Go to "Classes & Schedule".',
      'Open the "Class Types" tab.',
      'Type the name under "Add New Type" — for example "Zumba" or "CrossFit".',
      'Click "Add".',
    ],
    notes: [
      'Add types here rather than while creating a class — the quick-add inside the class form saves the name in lowercase.',
      'Removing a type does not change classes already using it.',
    ],
    related: ['create-class', 'schedule-class'],
    keywords: ['class type', 'category', 'discipline', 'type list', 'kind of class'],
    href: '/dashboard/class-types',
  },
  {
    id: 'schedule-class',
    category: 'classes',
    title: 'How do I schedule a class session?',
    summary: 'Put a class on the calendar, once or every week.',
    steps: [
      'Go to "Classes & Schedule".',
      'On the "Sessions" tab click "Schedule Session".',
      'Pick the "Branch" if you have more than one, then the "Class".',
      'Choose the "Session Type" — "Pop-up" for a one-off or "Recurring" for every week. It starts on "Recurring".',
      'Set the "Date", "Start Time" and "End Time".',
      'Choose the "Studio" — this is required.',
      'Optionally set the "Capacity" and the "Trainer", then click "Schedule".',
    ],
    notes: [
      'You need a studio for that branch first, or the session cannot be saved. Add one under Settings → "Branches & Operations".',
      'The class must be active to show up in the list.',
      '"Recurring" creates several weeks at once and tells you how many.',
      'New sessions are hidden from members until you publish the schedule.',
      'The "Sessions" tab shows this month only, so next month’s sessions will not be listed until you switch the filter to "All Sessions".',
    ],
    related: ['publish-schedule', 'create-class', 'cancel-session', 'edit-session', 'copy-month'],
    keywords: [
      'schedule class', 'book class', 'calendar', 'timetable', 'add session',
      'recurring', 'weekly', 'pop-up', 'one off', 'new session', 'put on schedule',
    ],
    href: '/dashboard/classes',
  },
  {
    id: 'publish-schedule',
    category: 'classes',
    title: 'Why can’t members see the schedule?',
    summary: 'The schedule stays hidden until you publish it.',
    steps: [
      'Go to "Classes & Schedule".',
      'Open the "Schedule" tab.',
      'Look at the banner at the top. "Schedule not published" means members cannot see anything yet.',
      'Click "Publish Schedule".',
      'After later changes the banner reads "Unpublished changes" — click "Push Changes" to send them to the app.',
    ],
    notes: [
      'Publishing covers sessions from today onwards.',
      'Every new session starts hidden, so publish again after each batch of changes.',
      'Hidden sessions show with a dashed border and an "Unpublished" tag.',
    ],
    related: ['schedule-class', 'copy-month', 'edit-session'],
    keywords: [
      'publish', 'not visible', 'members cant see', 'hidden', 'app not showing',
      'push changes', 'unpublished', 'go live', 'missing schedule', 'nothing showing',
    ],
    href: '/dashboard/classes',
  },
  {
    id: 'edit-session',
    category: 'classes',
    title: 'How do I change the time of a class?',
    summary: 'Edit one session, or the whole weekly series.',
    steps: [
      'Go to "Classes & Schedule" → "Sessions" tab.',
      'Click the edit action on the session.',
      'For a weekly class, choose under "Recurring Series" whether to "Apply to this session only" or "Apply to this and all upcoming sessions".',
      'Change the time or date and save.',
    ],
    notes: [
      'Applying to the whole series is selected by default. If you only mean to move one day, switch to "Apply to this session only" first.',
      'When applying to all, changing the date moves the whole series by the same number of days.',
      'Publish again afterwards so members see the new time.',
    ],
    related: ['schedule-class', 'cancel-session', 'publish-schedule'],
    keywords: ['edit session', 'change time', 'move class', 'reschedule', 'wrong time', 'series'],
    href: '/dashboard/classes',
  },
  {
    id: 'cancel-session',
    category: 'classes',
    title: 'How do I cancel a class?',
    summary: 'Cancel a session and let the booked members know.',
    steps: [
      'Go to "Classes & Schedule" → "Sessions" tab.',
      'Click the cancel action to open "Cancel Session".',
      'Type the "Cancellation Reason" — this is required.',
      'Leave "Notify booked members by email" on if you want them told.',
      'Click "Cancel Session".',
    ],
    notes: [
      'This cannot be undone. Cancelled sessions only show under the "Cancelled" filter.',
      'To end a weekly class for good, use "Stop this recurring series" on the "Schedule" tab — that cancels all future dates.',
    ],
    related: ['edit-session', 'schedule-class'],
    keywords: [
      'cancel class', 'cancel session', 'call off', 'trainer sick', 'closed',
      'stop series', 'delete session', 'no class today',
    ],
    href: '/dashboard/classes',
  },
  {
    id: 'copy-month',
    category: 'classes',
    title: 'How do I copy one month’s schedule to the next?',
    summary: 'Duplicate a month instead of typing it all again.',
    steps: [
      'Go to "Classes & Schedule" → "Schedule" tab.',
      'Click "Copy month to month".',
      'Choose the "From" and "To" months.',
      'Click "Copy Schedule".',
      'Publish the schedule so members see the new month.',
    ],
    notes: [
      'The month you copy into must be completely empty for that branch, otherwise it will refuse.',
      'Only weekly classes are copied — one-off pop-ups and cancelled sessions are skipped.',
      'It copies the branch selected on the "Schedule" tab.',
      'Copied sessions arrive hidden, so publish afterwards.',
    ],
    related: ['publish-schedule', 'schedule-class'],
    keywords: ['copy month', 'duplicate schedule', 'next month', 'repeat month', 'clone', 'bulk schedule'],
    href: '/dashboard/classes',
  },
  {
    id: 'manage-bookings',
    category: 'classes',
    title: 'How do I add someone to a class or mark them attended?',
    summary: 'Manage the booking list for one session.',
    steps: [
      'Go to "Classes & Schedule" → "Sessions" tab.',
      'Click the bookings action on the session.',
      'To add someone, click "Add Member", search, then click "Add" on their row.',
      'Use "Mark Attended", "Mark Absent" or "Reset to Booked" on each row.',
      'Use "Remove Booking" to take someone off.',
    ],
    notes: [
      '"Add Member" only shows while the session is still upcoming. For a class that has already happened, use "Manual Check-in" on the Attendance screen.',
      'Marking someone attended or absent does not change the number of spots booked.',
    ],
    related: ['schedule-class', 'check-in-member'],
    keywords: [
      'bookings', 'attendance list', 'add to class', 'mark attended', 'absent',
      'no show', 'roster', 'who booked', 'sign in sheet',
    ],
    href: '/dashboard/classes',
  },
  {
    id: 'add-trainer',
    category: 'classes',
    title: 'How do I add a trainer?',
    summary: 'Create a trainer profile with their own app login.',
    steps: [
      'Go to "Services" and open the tab for what they do — "Personal Training", "Physiotherapy" or "Nutrition".',
      'In the "Specialists" card click "Add Specialist".',
      'Enter their "Name" and pick the "Type".',
      'Set a "Username" (their mobile number) and a "Password", or click "Generate".',
      'Tick at least one branch under "Branches" — this is required.',
      'Optionally add a photo, bio and specialisations, then click "Add Specialist".',
      'Copy the login details from the confirmation screen before closing it.',
    ],
    notes: [
      'The password is shown only once. If you lose it, edit the trainer and set a new one.',
      'You need at least one branch before a trainer can be saved.',
      'The "Type" you pick decides which Services tab they appear under.',
    ],
    related: ['create-class', 'schedule-class', 'create-service-package'],
    keywords: [
      'add trainer', 'coach', 'instructor', 'specialist', 'physio',
      'nutritionist', 'pt', 'trainer login', 'coaches app', 'new trainer',
    ],
    href: '/dashboard/trainers',
  },
  {
    id: 'create-service-package',
    category: 'classes',
    title: 'How do I create a personal training package?',
    summary: 'Sell a bundle of one-to-one sessions.',
    steps: [
      'Go to "Services".',
      'Open the tab for the service — "Personal Training", "Physiotherapy" or "Nutrition".',
      'In the "Session Packages" card click "Add Package".',
      'Fill in "Package name *", "Sessions *" and "Price *".',
      'Click "Add package".',
    ],
    notes: [
      'The package is saved under whichever tab you were on, so check you are on the right one first.',
      'Packages are archived rather than deleted, so you can bring one back later.',
      'Sell the package by choosing it under "Service / Item" when you record a payment.',
    ],
    related: ['add-trainer', 'record-service-attendance', 'record-payment'],
    keywords: [
      'pt package', 'personal training', 'physio', 'nutrition', 'session pack',
      'bundle', '10 sessions', 'private session', 'one to one',
    ],
    href: '/dashboard/services',
  },

  // ── Attendance ──────────────────────────────────────────────────────
  {
    id: 'check-in-member',
    category: 'attendance',
    title: 'How do I check a member in manually?',
    summary: 'Log a visit when someone cannot scan the QR code.',
    steps: [
      'Go to "Attendance & Access".',
      'Click "Manual Check-in".',
      'Search for and select the member first.',
      'Set the "Check-in Date & Time" — it starts at now.',
      'Choose the "Entry Point" — either under "Gym Access (no session deducted)" or "Class Session (session deducted)".',
      'Click "Log Check-in".',
    ],
    notes: [
      'Pick the member before the entry point. The options depend on what their plan allows, and some plans are gym-only or class-only.',
      'Choosing a class session takes one session off their balance; gym access does not.',
      'Class options depend on the date you set, so change the date first if you are logging an earlier visit.',
    ],
    related: ['gym-qr-code', 'attendance-log', 'manage-bookings'],
    keywords: [
      'check in', 'checkin', 'manual', 'log entry', 'attendance', 'arrive',
      'scan failed', 'forgot phone', 'door', 'entry', 'sign in',
    ],
    href: '/dashboard/attendance',
  },
  {
    id: 'gym-qr-code',
    category: 'attendance',
    title: 'How do I print the gym check-in QR code?',
    summary: 'Get the QR code members scan at the entrance.',
    steps: [
      'Go to "Attendance & Access".',
      'Click "Gym QR Code".',
      'Pick the "Branch" if you have more than one.',
      'Click "Download PNG" or "Print".',
    ],
    notes: [
      'Each branch has its own code, so print one per location.',
      'Only use "Regenerate QR" if a code has leaked — it instantly stops every printed copy for that branch from working.',
    ],
    related: ['check-in-member', 'studio-qr-code'],
    keywords: ['qr code', 'print qr', 'scan', 'entrance', 'poster', 'download qr', 'check in code'],
    href: '/dashboard/attendance',
  },
  {
    id: 'studio-qr-code',
    category: 'attendance',
    title: 'How do I print a studio’s QR code?',
    summary: 'Put a permanent QR code on a studio door.',
    steps: [
      'Go to "Settings" → "Branches & Operations" and find the "Studios" tab.',
      'Find the studio and click "View QR Code".',
      'Click "Print" and put it up at the studio entrance.',
    ],
    notes: [
      'A studio code is permanent and cannot be regenerated, so print it once and mount it.',
      'Members scanning it are checked against their booking for that studio.',
    ],
    related: ['gym-qr-code', 'add-studio', 'schedule-class'],
    keywords: ['studio qr', 'room qr', 'class qr', 'print', 'studio access', 'door code'],
    href: '/dashboard/studios',
  },
  {
    id: 'attendance-log',
    category: 'attendance',
    title: 'How do I see who came in and when?',
    summary: 'Search the check-in history.',
    steps: [
      'Go to "Attendance & Access".',
      'Open the "Logs & Access" tab.',
      'Set the "From" and "To" dates, and pick a member or entry point if you want.',
      'Click "Apply Filters".',
    ],
    notes: [
      'The filters only take effect when you click "Apply Filters".',
      'The search box only looks at the page you are on, so set the dates first when looking over a long period.',
      'The "Live Feed" tab shows the latest check-ins and refreshes on its own.',
    ],
    related: ['check-in-member', 'member-attendance'],
    keywords: [
      'attendance log', 'history', 'who came', 'visits', 'report',
      'check in history', 'footfall', 'logs', 'busy times',
    ],
    href: '/dashboard/attendance?view=logs',
  },
  {
    id: 'member-attendance',
    category: 'attendance',
    title: 'How do I see one member’s attendance?',
    summary: 'Check a single member’s visits.',
    steps: [
      'Go to "Members" and open their profile.',
      'Switch to the "Attendance" tab.',
      'Read "Total Check-ins", "This Period" and "Last Visit", with the full history below.',
      'Use "Filter by date range" to narrow it down.',
    ],
    notes: ['This screen is read-only. To add a visit, use "Manual Check-in" on the Attendance screen.'],
    related: ['attendance-log', 'check-in-member'],
    keywords: [
      'member attendance', 'visits', 'last visit', 'how often', 'usage',
      'came in', 'history', 'not been in',
    ],
    href: '/dashboard/members',
  },
  {
    id: 'record-service-attendance',
    category: 'attendance',
    title: 'How do I record a PT session?',
    summary: 'Log a one-to-one session and take it off their package.',
    steps: [
      'Go to "Attendance & Access".',
      'Open the "Services Attendance" tab.',
      'Click "Record attendance".',
      'Choose the member, then the "Service package", then the "Specialist" — in that order.',
      'Set the "Date & time".',
      'Click "Deduct session".',
    ],
    notes: [
      'The member needs a package with sessions left, and the service needs a trainer set up.',
      'Made a mistake? Use "Reverse attendance" on the row — the session goes back onto their package.',
    ],
    related: ['create-service-package', 'add-trainer', 'deduct-session'],
    keywords: [
      'pt session', 'service attendance', 'deduct session', 'physio session',
      'nutrition', 'use a session', 'private session', 'log session',
    ],
    href: '/dashboard/attendance?view=services',
  },
  {
    id: 'deduct-session',
    category: 'attendance',
    title: 'How do I fix a member’s session count?',
    summary: 'Correct how many sessions a member has used.',
    steps: [
      'Go to "Classes & Schedule" and open the "Sessions Tracker" tab.',
      'Find the member under "Members Overview".',
      'Click "Session" to take one off straight away.',
      'To correct the total, click the sessions figure on their row, type the right number and save.',
    ],
    notes: [
      'The "Session" button is greyed out when they have none left.',
      'To give them more sessions, use "Add Sessions" on their profile instead.',
      '"Scan History" shows every session used and whether it came from a scan or was added by hand.',
    ],
    related: ['renew-membership', 'record-service-attendance'],
    keywords: [
      'sessions', 'session count', 'deduct', 'wrong count', 'correct sessions',
      'used sessions', 'remaining', 'tracker', 'balance', 'too many sessions',
    ],
    href: '/dashboard/sessions',
  },

  // ── Staff & roles ───────────────────────────────────────────────────
  {
    id: 'add-staff',
    category: 'staff',
    title: 'How do I add a staff member?',
    summary: 'Create a login for someone on your team.',
    steps: [
      'Go to "Staff & Roles" in the sidebar.',
      'On the "Staff Accounts" tab click "Add Staff".',
      'Fill in "Full Name *" and "Email *" — both required. "Phone" is optional.',
      'Under "Assign Roles", tick the roles they should have.',
      'Click "Create Staff".',
      'Copy the temporary password from the confirmation screen before closing it.',
    ],
    notes: [
      'A temporary password is created for you, and they must change it when they first sign in.',
      'It is only shown once. If you lose it, use "Reset Password" on their row.',
      'Create your roles first — someone with no roles can sign in but will not be able to open anything.',
    ],
    related: ['create-role', 'staff-permissions', 'reset-staff-password'],
    keywords: [
      'add staff', 'employee', 'receptionist', 'team', 'user', 'account',
      'front desk', 'manager', 'new user', 'login', 'staff login',
    ],
    href: '/dashboard/staff',
  },
  {
    id: 'create-role',
    category: 'staff',
    title: 'How do I create a role?',
    summary: 'Define a job role and what it can reach.',
    steps: [
      'Go to "Staff & Roles" and open the "Roles & Permissions" tab.',
      'Click "Create Role".',
      'Enter the "Role Name *" — for example "Manager" or "Receptionist".',
      'Under "Permissions", tick each area the role should reach. Clicking anywhere on a row ticks it.',
      'Click "Create Role".',
    ],
    notes: [
      'Access is all or nothing per area — there is no view-only option. Ticking an area lets that role add, edit and delete within it.',
      'Be careful with "Staff & Roles": anyone who has it can change roles, including their own.',
      'Deleting a role takes those permissions away from everyone who had it.',
    ],
    related: ['add-staff', 'staff-permissions'],
    keywords: ['role', 'create role', 'job title', 'permission group', 'manager role', 'receptionist'],
    href: '/dashboard/staff',
  },
  {
    id: 'staff-permissions',
    category: 'staff',
    title: 'How do I control what staff can see?',
    summary: 'Change which areas a staff member can reach.',
    steps: [
      'Go to "Staff & Roles" and open the "Roles & Permissions" tab.',
      'Select the role they have.',
      'Click "Edit" and tick or untick the areas.',
      'Click "Save Changes".',
      'To change which roles someone has, edit them on the "Staff Accounts" tab instead.',
    ],
    notes: [
      'Permissions come from roles, so changing a role affects everyone who has it.',
      'Ticking an area both shows its sidebar tab and unlocks everything inside it.',
      'A few screens sit under a different area than you might expect: trainers and studios come under "Classes & Schedule", branches under "Settings", and analytics under "Members".',
    ],
    related: ['create-role', 'add-staff', 'deactivate-staff'],
    keywords: [
      'permissions', 'access', 'roles', 'restrict', 'hide', 'cant see',
      'grant', 'limit staff', 'security', 'privileges',
    ],
    href: '/dashboard/staff',
  },
  {
    id: 'reset-staff-password',
    category: 'staff',
    title: 'How do I reset a staff member’s password?',
    summary: 'Give them a new temporary password.',
    steps: [
      'Go to "Staff & Roles" → "Staff Accounts" tab.',
      'Click the "Reset Password" action on their row.',
      'Copy the new password and share it with them.',
    ],
    notes: [
      'This happens straight away with no confirmation — their old password stops working immediately.',
      'The new one is shown only once, and they must change it at their next sign-in.',
    ],
    related: ['add-staff', 'deactivate-staff'],
    keywords: [
      'reset password', 'forgot password', 'locked out', 'cant login',
      'new password', 'staff password', 'password help',
    ],
    href: '/dashboard/staff',
  },
  {
    id: 'deactivate-staff',
    category: 'staff',
    title: 'How do I remove a staff member’s access?',
    summary: 'Switch off a staff account immediately.',
    steps: [
      'Go to "Staff & Roles" → "Staff Accounts" tab.',
      'Click "Deactivate" on their row.',
      'Confirm in the "Deactivate Account" box.',
      'Use "Reactivate" on the same row to restore access later.',
    ],
    notes: [
      'This takes away access straight away but keeps their record and history.',
      'Staff accounts cannot be deleted, only deactivated.',
    ],
    related: ['add-staff', 'staff-activity-log', 'reset-staff-password'],
    keywords: [
      'deactivate staff', 'remove access', 'revoke', 'left', 'resigned',
      'disable account', 'block staff', 'fired',
    ],
    href: '/dashboard/staff',
  },
  {
    id: 'staff-activity-log',
    category: 'staff',
    title: 'How do I see what my staff have been doing?',
    summary: 'Review and export the staff activity log.',
    steps: [
      'Go to "Staff & Roles" and open the "Activity Log" tab.',
      'Filter by name, a "From"/"To" date range, or a particular "Action".',
      'Click "Apply" — the filters do nothing until you do.',
      'Click "Export CSV" to download the results.',
    ],
    notes: ['The export covers everything matching your filters, not just the page on screen.'],
    related: ['deactivate-staff', 'staff-permissions'],
    keywords: [
      'activity log', 'audit', 'who did', 'history', 'changes',
      'track staff', 'accountability', 'who deleted',
    ],
    href: '/dashboard/staff',
  },

  // ── Content & notifications ─────────────────────────────────────────
  {
    id: 'send-notification',
    category: 'content',
    title: 'How do I send a notification to members?',
    summary: 'Send an announcement that arrives on their phone.',
    steps: [
      'Go to "Content" in the sidebar and open the "Communications" tab.',
      'Stay on "Compose".',
      'Fill in the "Title" and "Message" — both required.',
      'Under "Recipients", choose "All Active Members", or "Filter Members" to pick by status or plan.',
      'Leave "Send Time" on "Send Now".',
      'Click "Send Notification".',
    ],
    notes: [
      'Sending is immediate and cannot be undone. Only scheduled ones can be cancelled.',
      'You will see how many members it reached once it has gone.',
    ],
    related: ['schedule-notification', 'upload-banner', 'create-popup'],
    keywords: [
      'notification', 'push', 'announce', 'message members', 'broadcast',
      'alert', 'news', 'tell members', 'communications', 'text members',
    ],
    href: '/dashboard/notifications',
  },
  {
    id: 'schedule-notification',
    category: 'content',
    title: 'How do I schedule a notification for later?',
    summary: 'Set an announcement to go out at a future time.',
    steps: [
      'Go to "Content" → "Communications" → "Compose".',
      'Write the "Title" and "Message" and choose your recipients.',
      'Under "Send Time" choose "Schedule".',
      'Set the "Date & Time".',
      'Click "Schedule Notification".',
    ],
    notes: [
      'Scheduled messages sit under the "Scheduled" tab, where you can edit or cancel them.',
      'The time uses your computer’s clock, so double-check it if your computer is set to another country.',
    ],
    related: ['send-notification'],
    keywords: ['schedule notification', 'later', 'future', 'timed', 'plan message', 'cancel scheduled'],
    href: '/dashboard/notifications',
  },
  {
    id: 'upload-banner',
    category: 'content',
    title: 'How do I add a banner to the app?',
    summary: 'Manage the images members see in the app.',
    steps: [
      'Go to "Content" — "Banners" opens by default.',
      'Click "Add New Banner".',
      'Optionally add a caption, description, sort order and tag.',
      'Choose what tapping it does: "No action", "Open URL", "Internal screen" or "Sponsor offer".',
      'Click "Choose Image & Upload" and pick the image — the banner is created as soon as you choose it.',
    ],
    notes: [
      'Use images around 1170×534 pixels, JPG or PNG, under 500 KB. Larger ones still work but load slowly for members.',
      'Sort order runs lowest first, so 0 shows first.',
      'If you choose "Open URL" or "Internal screen" but do not set the destination, the banner shows a warning and will not work.',
    ],
    related: ['create-popup', 'send-notification', 'app-colors'],
    keywords: [
      'banner', 'image', 'carousel', 'slider', 'home screen', 'app image',
      'promo image', 'upload', 'advert', 'picture in app',
    ],
    href: '/dashboard/content',
  },
  {
    id: 'create-popup',
    category: 'content',
    title: 'How do I show a pop-up when members open the app?',
    summary: 'Create a message that appears on app open.',
    steps: [
      'Go to "Content" and open the "Pop-ups" tab.',
      'Click "Add New Pop-up".',
      'Enter the "Title *" — required.',
      'Optionally add a subtitle, button label, image and priority.',
      'Choose an action: "No action", "Open URL" or "Deep link to screen".',
      'Click "Create Pop-up".',
    ],
    notes: [
      'A higher priority number shows first — the opposite of banners, where 0 comes first.',
      'Only active pop-ups appear, and members see them when they open the app.',
    ],
    related: ['upload-banner', 'send-notification'],
    keywords: ['popup', 'pop-up', 'splash', 'app open', 'announcement', 'message on open'],
    href: '/dashboard/content',
  },
  {
    id: 'add-partner',
    category: 'content',
    title: 'How do I add a partner or sponsor?',
    summary: 'Show partner logos in the app.',
    steps: [
      'Go to "Content" and open the "Partners" tab.',
      'Click "Add Partner".',
      'Enter the "Name" — required.',
      'Click "Upload logo" and pick the image.',
    ],
    notes: ['Logos must be under 2 MB.'],
    related: ['upload-banner'],
    keywords: ['partner', 'sponsor', 'logo', 'brand', 'affiliate', 'collaboration'],
    href: '/dashboard/content',
  },
  {
    id: 'create-promo-code',
    category: 'content',
    title: 'How do I create a promo code?',
    summary: 'Create a discount code members can use.',
    steps: [
      'Go to "Promotions & Discounts" in the sidebar.',
      'On the "Promo Codes" tab click "New Code".',
      'Enter the "Code" (for example SUMMER20) and a "Name" — both required.',
      'Set the "Discount" — choose "%" or "Fixed" and enter the value.',
      'Optionally set the valid dates and usage limits.',
      'Click "Create Code".',
    ],
    notes: [
      'Set "Per Member Limit" to 1 to make it one use per member.',
      'Leave the limits blank for unlimited use.',
      'Promo codes cannot be deleted, only deactivated.',
      'Use "View Redemptions" on a row to see who used it.',
    ],
    related: ['plan-promo-price', 'record-payment', 'assign-plan'],
    keywords: [
      'promo code', 'coupon', 'voucher', 'discount code', 'code',
      'percent off', 'sale code', 'campaign',
    ],
    href: '/dashboard/promotions',
  },
  {
    id: 'plan-promo-price',
    category: 'content',
    title: 'How do I put a plan on sale?',
    summary: 'Set a temporary price on a membership plan.',
    steps: [
      'Go to "Promotions & Discounts" and open the "Plan Pricing" tab.',
      'Click "Set Promotion".',
      'Choose the "Membership Plan".',
      'Enter the "Promotional Price" and set "Valid From" and "Valid Until" — all required.',
      'Click "Set Promotion".',
    ],
    notes: [
      'Each plan can only have one promotion at a time.',
      'While it runs, the sale price appears automatically when you assign that plan or take a payment for it.',
      'The normal price comes back on its own when the promotion ends.',
    ],
    related: ['create-promo-code', 'edit-plan', 'assign-plan'],
    keywords: [
      'sale', 'plan price', 'promotional price', 'discount plan', 'special offer',
      'reduce price', 'temporary price', 'offer on plan',
    ],
    href: '/dashboard/promotions',
  },
  {
    id: 'create-app-offer',
    category: 'content',
    title: 'How do I create an offer for the app?',
    summary: 'Publish an offer members can see and buy in the app.',
    steps: [
      'Open the Offers screen.',
      'Click "New Offer".',
      'Enter the "Title" and the "Expiry Date" — both required.',
      'Add the description, prices, a tag and an image as needed.',
      'Optionally use "Link to Plan or Package" so buying it activates that plan automatically.',
      'Set the "Status" to "Active", then click "Create Offer".',
    ],
    notes: [
      'New offers start as "Draft" and members cannot see them until you set them to "Active".',
      'You can have up to 10 active offers at once.',
      'Deleting an offer is permanent — set it back to "Draft" if you might reuse it.',
    ],
    related: ['create-promo-code', 'upload-banner', 'create-plan'],
    keywords: [
      'offer', 'explore feed', 'app offer', 'deal', 'bundle',
      'sell in app', 'draft offer', 'promotion card',
    ],
    href: '/dashboard/offers',
  },

  // ── Settings ────────────────────────────────────────────────────────
  {
    id: 'gym-settings',
    category: 'settings',
    title: 'How do I change my gym’s name or logo?',
    summary: 'Edit the gym details members see in the app.',
    steps: [
      'Go to "Settings" in the sidebar.',
      'Click the "Gym Profile" section to open it.',
      'Click "Upload Logo" to change the logo — it saves as soon as you pick the file.',
      'Edit the "Gym Name" (required), plus the email, phone, address and description.',
      'Click "Save Profile".',
    ],
    notes: [
      'The logo saves on upload, but the text fields need "Save Profile".',
      'The description appears on the app’s opening screen.',
      'The gym timezone cannot be changed here — contact support if it is wrong.',
    ],
    related: ['app-colors', 'operating-hours', 'add-branch'],
    keywords: [
      'settings', 'logo', 'gym name', 'branding', 'profile', 'upload logo',
      'rename', 'contact details', 'address', 'timezone',
    ],
    href: '/dashboard/settings',
  },
  {
    id: 'app-colors',
    category: 'settings',
    title: 'How do I change the colours in the app?',
    summary: 'Set the brand colours members see.',
    steps: [
      'Go to "Settings" and open the "App Branding" section.',
      'Set the "Primary Color" — buttons, links and main highlights.',
      'Set the "Secondary Color" — badges and tags.',
      'Check the "Preview", then click "Save Colors".',
    ],
    notes: ['Members see the new colours the next time they open the app, not straight away.'],
    related: ['gym-settings', 'upload-banner'],
    keywords: ['colors', 'colours', 'brand', 'theme', 'app colors', 'appearance', 'branding'],
    href: '/dashboard/settings',
  },
  {
    id: 'operating-hours',
    category: 'settings',
    title: 'How do I set my opening hours?',
    summary: 'Set open and close times for each day.',
    steps: [
      'Go to "Settings" and open the "Branches & Operations" section.',
      'Find the "Operating Hours" card.',
      'Set the open and close time for each day.',
      'Tick "Closed" for any day you do not open.',
      'Click "Save Hours".',
    ],
    related: ['gym-settings', 'gym-capacity'],
    keywords: ['hours', 'opening hours', 'open', 'close', 'closed', 'times', 'working hours'],
    href: '/dashboard/settings',
  },
  {
    id: 'gym-capacity',
    category: 'settings',
    title: 'How do I show members how busy the gym is?',
    summary: 'Turn on the busyness indicator in the app.',
    steps: [
      'Go to "Settings" and open the "Branches & Operations" section.',
      'Find the "Gym Capacity" card.',
      'Turn on "Enable Capacity Tracking".',
      'Enter your "Maximum Gym Capacity".',
      'Click "Save".',
    ],
    notes: [
      'Busyness is worked out from check-ins in the last two hours, so members need to be checking in for it to be right.',
      '"Live Preview" shows what members see now.',
    ],
    related: ['operating-hours', 'gym-qr-code'],
    keywords: ['capacity', 'busy', 'crowded', 'how busy', 'occupancy', 'max people'],
    href: '/dashboard/settings',
  },
  {
    id: 'contract-terms',
    category: 'settings',
    title: 'How do I publish my terms and conditions?',
    summary: 'Set the terms members see in the app and on invoices.',
    steps: [
      'Go to "Settings" and open the "Contract Terms" section.',
      'Type or paste your terms into "Terms content".',
      'Click "Publish Terms".',
    ],
    notes: [
      'Leave a blank line between paragraphs, and start a line with "-" for a bullet point.',
      'Each time you publish, a new version is saved. Invoices already sent keep the version they were issued under.',
    ],
    related: ['gym-settings', 'view-invoice'],
    keywords: ['terms', 'conditions', 'contract', 'policy', 'agreement', 'legal', 'rules'],
    href: '/dashboard/settings',
  },
  {
    id: 'mobile-app-settings',
    category: 'settings',
    title: 'How do I turn mobile payments or session sharing on and off?',
    summary: 'Control what members can do in the app.',
    steps: [
      'Go to "Settings" and open the "Mobile App & Payments" section.',
      'Use "Mobile Payments" to allow or block paying in the app.',
      'Use "Session Transfers" to allow or block members sharing sessions.',
      'Click "Save".',
    ],
    notes: ['Flipping a switch does nothing until you press "Save".'],
    related: ['payment-gateway', 'transfer-membership'],
    keywords: [
      'mobile payments', 'session transfers', 'app settings', 'turn off',
      'disable payments', 'share sessions', 'toggle',
    ],
    href: '/dashboard/settings',
  },
  {
    id: 'add-branch',
    category: 'settings',
    title: 'How do I add a branch or location?',
    summary: 'Add another gym location.',
    steps: [
      'Go to "Settings" and open the "Branches & Operations" section.',
      'On the "Branches" tab click "Add Branch".',
      'Enter the branch name — required.',
      'Optionally add the address and a Google Maps link.',
      'Click "Create".',
    ],
    notes: [
      'Extra branches may cost more per month, and your plan has a limit. When you reach it the "Add Branch" button disappears and you will need to contact support.',
      'Deactivate rather than delete a branch you might reopen — deleting is permanent.',
    ],
    related: ['add-studio', 'gym-settings'],
    keywords: ['branch', 'location', 'second gym', 'new site', 'multi branch', 'another gym'],
    href: '/dashboard/branches',
  },
  {
    id: 'add-studio',
    category: 'settings',
    title: 'How do I add a studio or room?',
    summary: 'Create the rooms your classes run in.',
    steps: [
      'Go to "Settings" → "Branches & Operations" and open the "Studios" tab.',
      'Click "New Studio".',
      'Pick the "Branch" if you have more than one, and enter the "Studio name".',
      'Click "Create Studio".',
    ],
    notes: [
      'You need at least one studio before you can put any class on the calendar.',
      'Deleting a studio leaves its scheduled classes without a room.',
    ],
    related: ['add-branch', 'schedule-class', 'studio-qr-code'],
    keywords: ['studio', 'room', 'hall', 'space', 'area', 'court', 'add room'],
    href: '/dashboard/studios',
  },
  {
    id: 'change-language',
    category: 'settings',
    title: 'How do I switch the admin panel to Arabic?',
    summary: 'Change the language of the screens you see.',
    steps: [
      'Open the account menu at the top right.',
      'Use the "Language" switcher.',
      'Choose "English" or "العربية".',
    ],
    notes: [
      'Arabic switches the whole panel to a right-to-left layout.',
      'This only changes what you see — it does not change the language for members or other staff.',
    ],
    related: ['dark-mode', 'gym-settings'],
    keywords: ['language', 'arabic', 'english', 'عربي', 'translate', 'switch language'],
  },
  {
    id: 'dark-mode',
    category: 'settings',
    title: 'How do I switch between dark and light mode?',
    summary: 'Change how the admin panel looks.',
    steps: [
      'Look at the top right of any page.',
      'Click the theme toggle.',
    ],
    notes: ['Your choice is remembered next time you sign in.'],
    related: ['change-language'],
    keywords: ['dark mode', 'light mode', 'theme', 'night', 'bright', 'appearance', 'eyes'],
  },
];
