[phases.setup]
nixPkgs = ["php83", "php83Extensions.pgsql", "php83Extensions.pdo_pgsql", "php83Extensions.mbstring", "php83Extensions.tokenizer", "php83Extensions.xml", "php83Extensions.ctype", "php83Extensions.curl", "php83Extensions.fileinfo", "php83Extensions.openssl"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader"]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=8080"
